# Generated by Django 3.0.5 on 2020-04-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
