# Generated by Django 3.0.5 on 2020-04-25 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0007_auto_20200425_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 15, 54, 16, 382700, tzinfo=utc)),
        ),
    ]
