# Generated by Django 3.0.5 on 2020-04-26 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0014_auto_20200426_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.TextField(default='No selected Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 9, 19, 5, 603684, tzinfo=utc)),
        ),
    ]
