# Generated by Django 3.0.5 on 2020-04-26 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0016_auto_20200426_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 9, 45, 49, 503778, tzinfo=utc)),
        ),
    ]
