# Generated by Django 3.0.5 on 2020-04-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0017_auto_20200426_1045'),
        ('QuarenPlanner', '0016_auto_20200426_1047'),
    ]

    operations = [
    ]
