# Generated by Django 3.0.5 on 2020-04-26 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0019_auto_20200426_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(choices=[('BK', 'Books'), ('BY', 'Beauty'), ('TC', 'Technology'), ('CR', 'Crafts'), ('MU', 'Music'), ('QU', 'Quiz'), ('NA', 'Other')], default='Other'),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 11, 50, 8, 30317, tzinfo=utc)),
        ),
    ]
