# Generated by Django 3.0.5 on 2020-04-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0021_auto_20200426_1303'),
        ('QuarenPlanner', '0018_merge_20200426_1123'),
    ]

    operations = [
    ]
