# Generated by Django 3.0.5 on 2020-04-26 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0022_merge_20200426_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(choices=[('BK', 'Books'), ('BY', 'Beauty'), ('TC', 'Technology'), ('CR', 'Crafts'), ('MU', 'Music'), ('QU', 'Quiz'), ('NA', 'Other')], default='Other'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 12, 5, 13, 313595, tzinfo=utc)),
        ),
    ]
