# Generated by Django 3.0.5 on 2020-04-26 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0022_auto_20200426_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(choices=[('CU', 'Culture'), ('BY', 'Beauty'), ('TC', 'Technology'), ('CR', 'Crafts'), ('MU', 'Music'), ('QU', 'Quiz'), ('NA', 'Other')], default='Other'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 12, 25, 49, 203220, tzinfo=utc)),
        ),
    ]
