# Generated by Django 3.0.5 on 2020-04-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0024_auto_20200426_1306'),
        ('QuarenPlanner', '0025_auto_20200426_1329'),
    ]

    operations = [
    ]
