# Generated by Django 3.0.5 on 2020-04-26 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0028_auto_20200426_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 14, 4, 2, 848640, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 24, 14, 4, 2, 848620, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 14, 4, 2, 848668, tzinfo=utc)),
        ),
    ]
