# Generated by Django 3.0.5 on 2020-04-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0028_auto_20200426_1442'),
        ('QuarenPlanner', '0026_merge_20200426_1330'),
    ]

    operations = [
    ]
