# Generated by Django 3.0.5 on 2020-04-26 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0032_auto_20200426_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 27, 14, 450820, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 24, 15, 27, 14, 450793, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 15, 27, 14, 450855, tzinfo=utc)),
        ),
    ]
