# Generated by Django 3.0.5 on 2020-04-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0033_auto_20200426_1627'),
        ('QuarenPlanner', '0029_merge_20200426_1444'),
    ]

    operations = [
    ]
