# Generated by Django 3.0.5 on 2020-04-26 15:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QuarenPlanner', '0034_merge_20200426_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(choices=[('Culture', 'Culture'), ('Beauty', 'Beauty'), ('Technology', 'Technology'), ('Crafts', 'Crafts'), ('Music', 'Music'), ('Quiz', 'Quiz'), ('Other', 'Other')], default='Other'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 28, 15, 57, 45, 279071, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 24, 15, 57, 45, 279051, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 15, 57, 45, 279099, tzinfo=utc)),
        ),
    ]
