# Generated by Django 3.0.5 on 2020-04-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('platform', models.TextField()),
                ('host', models.TextField()),
                ('event_start', models.DateTimeField(blank=True, default=None, null=True)),
                ('event_end', models.DateTimeField(blank=True, default=None, null=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='event_pictures')),
            ],
        ),
    ]
